settings = {'S1': {'s': 8,
                   'p': 2,
                   'stype': 'simple',
                   'xseed': 12},
            'S2': {'s': 6,
                   'p': 2,
                   'stype': 'parallel',
                   'xseed': 2,
                   'seed': 5},
            'S3': {'s': 6,
                   'p': 2,
                   'stype': 'interacted',
                   'xseed': 1,
                   'seed': 686},
            'S3nx': {'s': 6,
                     'p': 2,
                     'stype': 'interacted',
                     'xseed': 1,
                     'seed': 686,
                     'noint': True},
            'S3mod': {'s': 6,
                      'p': 2,
                      'stype': 'interacted',
                      'xseed': 1,
                      'seed': 686,
                      'moderator': True},
            'S4': {'s': 38,
                   'p': 2,
                   'stype': 'interacted',
                   'xseed': 4,
                   'seed': 3,
                   'degree': 8,
                   'zero_chance': 0.5},
            'S5': {'s': 6,
                   'p': 18,
                   'stype': 'interacted',
                   'xseed': 5,
                   'seed': 3,
                   'degree': 4,
                   'zero_chance': 0.6},
            'S6': {'s': 10,
                   'p': 22,
                   'stype': 'interacted',
                   'xseed': 6,
                   'seed': 1,
                   'degree': 6,
                   'zero_chance': 0.6}
           }